name: Build OpenWrt N30Pro
on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/bfdeh/openwrt.git
  REPO_BRANCH: main
  FEED_CONF: feeds.conf.default
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ github.repository }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ github.repository }}-ccache-

      - name: Fix dpkg lock & update apt
        run: |
          sudo rm -f /var/lib/apt/lists/lock
          sudo rm -f /var/lib/dpkg/lock-frontend
          sudo dpkg --configure -a
          sudo apt-get update

      - name: Install basic build packages
        run: |
          sudo apt-get install -y build-essential flex bison g++ gawk gcc-multilib g++-multilib gettext libncurses5-dev libssl-dev ccache

      - name: Install python & file tools
        run: |
          sudo apt-get install -y python3 python3-pip python3-setuptools python3-dev rsync unzip wget git subversion libz-dev file

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean

      - name: Setup ccache
        run: |
          ccache --set-config=max_size=5G
          ccache --set-config=cache_dir=~/.ccache
          echo "CCACHE_DIR=~/.ccache" >> $GITHUB_ENV

      - name: Download OpenWrt source
        run: |
          git clone --depth=1 -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} openwrt
          cd openwrt
          cp ../${{ env.FEED_CONF }} feeds.conf.default
          cp ../${{ env.CONFIG_FILE }} .config

      - name: Update & Install feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Download package sources
        run: |
          cd openwrt
          make download -j$(nproc)

      - name: Build firmware
        run: |
          cd openwrt
          export PATH="/usr/lib/ccache:$PATH"
          make -j$(nproc) world

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v5
        with:
          name: OpenWrt-N30Pro-Firmware
          path: openwrt/bin/targets/mediatek/filogic
